---
- name: First Play
  hosts: routers
  gather_facts: False
  connection: local
  tasks:
   - name: First Task
     ios_command:
         commands:show version
     register: version
   - name: second task
     debug:
         var: version
